"""
intent_processor.py
-------------------
ARIA intent decomposition engine.

At startup: loads schema_reference.json (generated by bootstrap_schema.py).
Falls back to hardcoded taxonomy if file is missing.

Domain + table scope constrained to user's security_profile.domains at classify time.
RAG files filtered to allowed domains → injected as available unstructured sources.
"""

import json
import re
import os
import logging
from collections import defaultdict
from typing import Optional

from core.groq_client import LLMClient
from core.rag_retriever import retrieve_chunks

logger = logging.getLogger("aria.intent_processor")

_SCHEMA_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "schema_reference.json")

# Compact 3-intent example for LLM few-shot (covers Structured, Unstructured, and Both)
_SCHEMA_EXAMPLE = (
    '{"original_query":"...","total_intents":3,"intents":['
    '{"intent_id":1,"description":"Fetch total revenue by region for Q1 2026",'
    '"domain":"Sales","sub_domain":"Order Tracking","data_source":"Structured",'
    '"structured_table":"fact_orders","relevant_columns":["region","revenue_usd","order_date"],'
    '"unstructured_source":null,'
    '"intent_types":["Data"],"requires_data_fetch":true,"requires_reasoning":false,"requires_action":false},'
    '{"intent_id":2,"description":"Retrieve cancellation eligibility rules and refund timelines from policy document",'
    '"domain":"Sales","sub_domain":"Cancellation","data_source":"Unstructured",'
    '"structured_table":null,"relevant_columns":[],'
    '"unstructured_source":"Cancellation_Policy_2026.pdf — Eligibility rules and refund timelines",'
    '"intent_types":["Data"],"requires_data_fetch":true,"requires_reasoning":false,"requires_action":false},'
    '{"intent_id":3,"description":"Fetch raw sales order cancellation records to apply policy rules for eligibility and refund status",'
    '"domain":"Sales","sub_domain":"Cancellation","data_source":"Both",'
    '"structured_table":"sales_cancellation","relevant_columns":["order_id","order_date","cancellation_date","order_value","refund_amount","cancellation_reason","cancellation_status"],'
    '"unstructured_source":"Cancellation_Policy_2026.pdf — Eligibility rules and refund timelines",'
    '"intent_types":["Data","Reasoning"],"requires_data_fetch":true,"requires_reasoning":true,"requires_action":false}'
    ']}'
)

# Hardcoded fallback if schema_reference.json is missing
_FALLBACK_TAXONOMY = {
    "Sales":    ["Order_Tracking", "Booking", "Cancellation", "Shipment", "Pricing"],
    "Finance":  ["Invoicing", "Payment", "Accounting", "Budget", "Tax_Compliance"],
    "HR":       ["Workforce", "Payroll", "Expense_Management"],
    "Logistics":["Inventory", "Warehouse", "Freight"],
    "Operations":["Returns", "SLA_Monitoring", "Quality_Control"],
}


def _load_schema() -> Optional[dict]:
    path = os.path.normpath(_SCHEMA_FILE)
    if not os.path.exists(path):
        logger.warning("schema_reference.json not found at %s — using fallback taxonomy", path)
        return None
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        logger.info(
            "Loaded schema_reference.json: %d domains, %d subdomains, %d tables, %d RAG files",
            len(data.get("domains", [])),
            len(data.get("subdomains", [])),
            len(data.get("tables", [])),
            len(data.get("rag_files", [])),
        )
        return data
    except Exception as e:
        logger.error("Failed to load schema_reference.json: %s — using fallback", e)
        return None


class IntentProcessor:
    def __init__(self, llm_config: dict = None) -> None:
        llm_cfg = llm_config or {}
        self._client = LLMClient(
            model=llm_cfg.get("model"),
            temperature=llm_cfg.get("temperature", 0.05),
            max_tokens=llm_cfg.get("max_tokens", 4096),
        )
        self._schema = _load_schema()  # None → fallback mode

    def reload_schema(self) -> None:
        """Hot-reload schema reference without restarting."""
        self._schema = _load_schema()

    def process(
        self,
        query: str,
        allowed_domains: Optional[list[str]] = None,
        allowed_subdomains: Optional[list[str]] = None,
        allowed_domain_ids: Optional[list[int]] = None,
        conversation_context: str = "",
    ) -> dict:
        taxonomy, tables_block, rag_block = self._build_scope(allowed_domains, allowed_subdomains)
        prompt = self._build_prompt(query, taxonomy, tables_block, rag_block, conversation_context)
        raw = self._client.generate(prompt)
        result = self._parse(raw)

        # ── out-of-scope guard ─────────────────────────────────
        if result.get("out_of_scope"):
            logger.info("ARIA: query out of scope — %s", result.get("reason", ""))
            return {
                "out_of_scope": True,
                "reason": result.get("reason", "This query is outside your accessible data domains."),
                "intents": [],
                "total_intents": 0,
                "original_query": query,
            }

        # ── post-validate structured tables against allowed scope ──
        if allowed_domains and result.get("intents"):
            allowed_lower = {d.lower() for d in allowed_domains}
            allowed_table_names = {
                t["table_name"].lower()
                for t in (self._schema.get("tables", []) if self._schema else [])
                if t.get("domain", "").lower() in allowed_lower
            }
            if allowed_table_names:
                for intent in result["intents"]:
                    tbl = (intent.get("structured_table") or "").lower()
                    if tbl and tbl not in allowed_table_names:
                        logger.warning(
                            "ARIA: intent '%s' mapped to out-of-scope table '%s' — marking out_of_scope",
                            intent.get("description", "")[:60], tbl,
                        )
                        return {
                            "out_of_scope": True,
                            "reason": f"The data required for this query ('{tbl}') is not within your accessible domains.",
                            "intents": [],
                            "total_intents": 0,
                            "original_query": query,
                        }

        # ── RAG retrieval for Unstructured / Both intents ──────
        if allowed_domain_ids:
            intents = result.get("intents", [])
            for intent in intents:
                if intent.get("data_source") in ("Unstructured", "Both"):
                    desc = intent.get("description", query)
                    chunks = retrieve_chunks(
                        intent_description=desc,
                        allowed_domain_ids=allowed_domain_ids,
                        top_k=5,
                    )
                    intent["retrieved_context"] = chunks
                else:
                    intent["retrieved_context"] = []
            result["intents"] = intents

        logger.info(
            "Classified: '%s…' → %d intent(s)",
            query[:60], result.get("total_intents", len(result.get("intents", [])))
        )
        return result

    # ── scope builder ──────────────────────────────────────────

    def _build_scope(
        self,
        allowed_domains: Optional[list[str]],
        allowed_subdomains: Optional[list[str]],
    ) -> tuple[str, str, str]:
        """
        Returns (taxonomy_str, tables_block_str, rag_block_str)
        All filtered to user's allowed scope.
        """
        if self._schema is None:
            return self._fallback_scope(allowed_domains)

        all_domains    = self._schema.get("domains", [])
        all_subdomains = self._schema.get("subdomains", [])
        all_tables     = self._schema.get("tables", [])
        all_rag        = self._schema.get("rag_files", [])

        # ── filter by allowed_domains ──────────────────────────
        if allowed_domains:
            allowed_lower = {d.lower() for d in allowed_domains}
            filtered_domains = [d for d in all_domains if d["name"].lower() in allowed_lower]
            allowed_ids = {d["id"] for d in filtered_domains}
            filtered_subs = [s for s in all_subdomains if s["domain_id"] in allowed_ids]
            filtered_rag  = [f for f in all_rag if f["domain"].lower() in allowed_lower]
        else:
            filtered_domains = all_domains
            filtered_subs    = all_subdomains
            filtered_rag     = all_rag

        if not filtered_domains:
            logger.warning("Domain filter produced empty taxonomy — falling back to full scope")
            filtered_domains = all_domains
            filtered_subs    = all_subdomains
            filtered_rag     = all_rag

        # ── build taxonomy string ──────────────────────────────
        sub_by_domain: dict[str, list[str]] = defaultdict(list)
        domain_id_to_name = {d["id"]: d["name"] for d in filtered_domains}
        for s in filtered_subs:
            dname = domain_id_to_name.get(s["domain_id"])
            if dname:
                sub_by_domain[dname].append(s["name"])

        taxonomy = "|".join(
            f"{dname}({','.join(subs)})" if subs else dname
            for dname, subs in sub_by_domain.items()
        ) or "|".join(d["name"] for d in filtered_domains)

        # ── filter tables to allowed domains ──────────────────
        # Tables tagged with domain field (new multi-domain schema) → filter.
        # Legacy tables without domain field → always include (backward compat).
        if allowed_domains:
            allowed_lower = {d.lower() for d in allowed_domains}
            filtered_tables = [
                t for t in all_tables
                if not t.get("domain") or t["domain"].lower() in allowed_lower
            ]
        else:
            filtered_tables = all_tables

        # ── build tables block (compact: table(col:type,...)) ──
        table_lines = []
        for t in filtered_tables:
            cols = ", ".join(f"{c['name']}:{c['type']}" for c in t["columns"])
            table_lines.append(f"  {t['table_name']}({cols})")
        tables_block = "\n".join(table_lines) if table_lines else "  (no tables available)"

        # ── build RAG block ────────────────────────────────────
        rag_lines = []
        for f in filtered_rag:
            desc = (f.get("description") or "").strip()
            brief = (desc[:80] + "…") if len(desc) > 80 else desc
            cat = f.get("sub_category") or f.get("category", "")
            entry = f"  {f['filename']} [{f['domain']} › {f['subdomain']}]"
            if cat:
                entry += f" [{cat}]"
            if brief:
                entry += f" — {brief}"
            rag_lines.append(entry)
        rag_block = "\n".join(rag_lines) if rag_lines else "  (no documents available)"

        return taxonomy, tables_block, rag_block

    def _fallback_scope(self, allowed_domains: Optional[list[str]]) -> tuple[str, str, str]:
        """Fallback when schema_reference.json missing."""
        taxonomy_dict = _FALLBACK_TAXONOMY
        if allowed_domains:
            allowed_lower = {d.lower() for d in allowed_domains}
            taxonomy_dict = {k: v for k, v in _FALLBACK_TAXONOMY.items() if k.lower() in allowed_lower}
        if not taxonomy_dict:
            taxonomy_dict = _FALLBACK_TAXONOMY
        taxonomy = "|".join(f"{d}({','.join(s)})" for d, s in taxonomy_dict.items())
        return taxonomy, "  (schema not available — run bootstrap_schema.py)", "  (no documents available)"

    # ── prompt builder ─────────────────────────────────────────

    def _build_prompt(self, query: str, taxonomy: str, tables_block: str, rag_block: str, conversation_context: str = "") -> str:
        context_block = ""
        if conversation_context and conversation_context.strip():
            context_block = (
                f"CONVERSATION CONTEXT (chat summary + recent turns):\n"
                f"{conversation_context}\n"
                f"CONTEXT RULE:\n"
                f"  1. BACK-REFERENCE DETECTION — treat the query as a back-reference (referring to prior turn) when it contains ANY of:\n"
                f"     Explicit: 'same', 'same stats', 'same data', 'same results', 'same figures', 'same metrics', 'same numbers',\n"
                f"               'those', 'those results', 'that table', 'that report', 'that document', 'the above', 'from the above',\n"
                f"               'previous', 'compare with previous', 'filter further', 'drill down', 'break it down', 'break down further'.\n"
                f"     Implicit: 'what about [X]', 'how about [X]', 'and for [X]', 'also for [X]', 'similar for [X]',\n"
                f"               'now show [X]', 'do the same for [X]', 'repeat for [X]', 'give me [X] for [year/region/category]'\n"
                f"               where the noun ('stats','data','numbers','summary','breakdown','report') matches prior turn.\n"
                f"     Time substitution: a query that changes ONLY the time period (year/month/quarter/date range) relative to\n"
                f"               the prior turn is ALWAYS a back-reference — e.g. prior='for 2024', current='for 2023' or 'last year'.\n"
                f"  2. STRUCTURED BACK-REFERENCE — when back-reference detected and context shows data_source:Structured:\n"
                f"     LOCK domain AND structured_table to exact values in context. Keep same relevant_columns unless query adds new ones.\n"
                f"     Apply any new filter (year, region, category) as a WHERE condition, NOT as a domain change.\n"
                f"  3. UNSTRUCTURED BACK-REFERENCE — when back-reference detected and context shows data_source:Unstructured:\n"
                f"     LOCK domain to context domain. Set data_source=Unstructured. Set unstructured_source to the EXACT filename\n"
                f"     shown in context (source: field). Apply new filters (year, region) in the intent description for SPYDER to use.\n"
                f"     Do NOT switch to a different document unless the query explicitly names one.\n"
                f"  4. BOTH BACK-REFERENCE — when context shows data_source:Both: lock both structured_table AND unstructured_source.\n"
                f"     UNKNOWN SOURCE — when context shows data_source:Unknown or no table and no source: lock domain only;\n"
                f"     classify data_source fresh (Structured/Unstructured/Both) based on query and available TABLES/DOCUMENTS.\n"
                f"  5. DOMAIN-LIKE TERMS ARE FILTERS — words matching domain/sub-domain names appearing after a back-reference\n"
                f"     (e.g. 'Sales', 'HR', 'Operations') are DATA FILTER VALUES (WHERE clause), NOT signals to switch domain.\n"
                f"  6. INDEPENDENT QUERY — if the query has NO back-reference signals from Rule 1, ignore context entirely and\n"
                f"     classify fresh from the TAXONOMY and STRUCTURED TABLES.\n\n"
            )
        return (
            "You are ARIA, an enterprise data analyst. "
            "Decompose the QUERY into atomic intents. "
            "Your entire response must begin with { and end with } — no markdown, no text outside JSON.\n\n"

            f"{context_block}"
            f"TAXONOMY (only classify within these domains/sub-domains):\n{taxonomy}\n\n"

            f"STRUCTURED TABLES (schema.table with columns — pick exact table name):\n{tables_block}\n\n"

            f"UNSTRUCTURED DOCUMENTS (available RAG files — reference by exact filename):\n{rag_block}\n\n"

            "RULES:\n"
            "data_source values:\n"
            "  Structured  = fetch records from a DB table only (structured_table set, unstructured_source null)\n"
            "  Unstructured= fetch information from a PDF/document/KB only (structured_table null, unstructured_source set)\n"
            "  Both        = single question that needs raw DB records AND rules/thresholds from a KB document to answer;\n"
            "                structured_table AND unstructured_source must BOTH be set;\n"
            "                SQL for Both intents fetches raw columns only — SPYDER applies KB rules after retrieval;\n"
            "                do NOT split into Structured+Unstructured when one question requires both sources together.\n"
            "data_source selection priority:\n"
            "  PREFER Unstructured when the question asks about: policies, procedures, rules, guidelines, eligibility,\n"
            "    timelines, escalation paths, who handles/owns/approves, responsibilities, conditions, exceptions,\n"
            "    refund rules, SLA definitions, compliance requirements, or any 'how does X work' / 'what is the process'.\n"
            "    Use Unstructured EVEN IF a structured table exists that might partially answer — if a relevant document\n"
            "    exists in UNSTRUCTURED DOCUMENTS, it is the authoritative source for policy/process questions.\n"
            "  PREFER Structured when the question asks for: raw records, counts, aggregations, specific field values,\n"
            "    transaction data, historical data, metrics, KPIs, or 'list all X' / 'how many' / 'show me the data'.\n"
            "  USE Both when a single question needs raw DB records to apply policy rules from a document (e.g. validate\n"
            "    eligibility of specific orders against cancellation policy).\n"
            "intent_types: Data=fetch/list/retrieve | Reasoning=compare/analyse/validate | Action=create/update/notify\n"
            "structured_table: exact table name from STRUCTURED TABLES list, or null\n"
            "relevant_columns: list column names from that table relevant to this intent, or []\n"
            "unstructured_source: 'filename — brief description' from UNSTRUCTURED DOCUMENTS, or null\n"
            "ONLY classify within provided TAXONOMY — never invent domains or sub-domains\n"
            "If the query cannot be answered using the available TAXONOMY and STRUCTURED TABLES, "
            "respond ONLY with: {\"out_of_scope\": true, \"reason\": \"<one sentence why>\", \"intents\": []}\n"
            "Order: Data intents first, Reasoning second, Action last\n"
            "One operation = one intent. Conditional action = separate intent.\n\n"

            f"EXAMPLE OUTPUT:\n{_SCHEMA_EXAMPLE}\n\n"

            f"QUERY: {query}"
        )

    # ── parser ─────────────────────────────────────────────────

    @staticmethod
    def _parse(text: str) -> dict:
        text = text.strip()
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
        text = text.strip()
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            match = re.search(r"\{.*\}", text, re.DOTALL)
            if match:
                return json.loads(match.group())
            raise ValueError(
                f"Model did not return valid JSON.\n\nRaw output (first 400 chars):\n{text[:400]}"
            )
